spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.8.118:5432/postgres?currentSchema=hibernate_practice
    username: test
    password: test
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    database: postgresql

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG